name: DiscordBridge
version: 1.1
main: me.discordBridge.DiscordBridge
api-version: '1.21'

commands:
  discordbridge:
    description: Shows the status of the Discord Bridge
    usage: /discordbridge status